### ISSUE TITLE
www-client/ungoogled-chromium-102.0.5005.61_p3: Crashes in "Control your music, videos, and more"

### ISSUE THREAD

**Issue by arbitrary-dev** [PF4Public/gentoo-overlay#156] opened 2022-06-04 18:38 UTC
### What were you trying to accomplish?

Run a YouTube video in picture-in-picture mode.

### What didn't function as expected?

App crashes.

#### Steps:

1. Run `chromium`
2. Browse some YT video (could be any video in browser)
3. Click "Control your music, videos, and more" button ![button-1](https://user-images.githubusercontent.com/6984946/173204573-7c52c3e1-bede-4652-aad8-fe5f38d5eb11.png)
4. If app not crashes yet, then click "picture-in-picture mode" button ![button-2](https://user-images.githubusercontent.com/6984946/173204612-dbf4981c-55a5-4bcc-8cba-8c4c0f42f4b6.png)
5. Now app crashes for certain

```
$ chromium-browser --enable-features=UseOzonePlatform --ozone-platform=wayland
[12432:12453:0604/212611.777430:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.Notifications exited with status 1
[12468:12468:0604/212611.785132:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is
[12432:12432:0604/212611.875958:ERROR:system_web_app_manager.cc(315)] Exceeded SWA install retry attempts.  Skipping installation, will retry on next OS update or when locale changes.
[12432:12461:0604/212612.340889:ERROR:ev_root_ca_metadata.cc(290)] Failed to register OID: 0
<CRASH_HAPPENS_HERE>
zsh: trace trap  chromium-browser --enable-features=UseOzonePlatform --ozone-platform=wayland
```

I'm using:
- dev-libs/wayland-1.20.0
- gui-wm/sway-1.7

**Comment by arbitrary-dev** [comment] 2022-06-04 18:40
```
$ equery u mesa
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for media-libs/mesa-22.0.3:
 U I
 + + X                    : Add support for X11
 - - abi_x86_32           : 32-bit (x86) libraries
 + + cpu_flags_x86_sse2   : Use the SSE2 instruction set
 - - d3d9                 : Enable Direct 3D9 API through Nine state tracker.
                            Can be used together with patched wine.
 - - debug                : Enable extra debug codepaths, like asserts and
                            extra output. If you want to get meaningful
                            backtraces see https://wiki.gentoo.org/wiki/Project
                            :Quality_Assurance/Backtraces
 - - gles1                : Enable GLESv1 support.
 + + gles2                : Enable GLESv2 support.
 + + llvm                 : Enable LLVM backend for Gallium3D.
 - - lm-sensors           : Enable Gallium HUD lm-sensors support.
 - - opencl               : Enable the Clover Gallium OpenCL state tracker.
 - - osmesa               : Build the Mesa library for off-screen rendering.
 - - test                 : Enable dependencies and/or preparations necessary
                            to run tests (usually controlled by FEATURES=test
                            but can be toggled independently)
 - - unwind               : Add support for call stack unwinding and function
                            name resolution
 + + vaapi                : Enable Video Acceleration API for hardware decoding
 - - valgrind             : Compile in valgrind memory hints
 - - vdpau                : Enable the VDPAU acceleration interface for the
                            Gallium3D Video Layer.
 - - video_cards_intel    : VIDEO_CARDS setting to build driver for Intel video
                            cards
 - - video_cards_nouveau  : VIDEO_CARDS setting to build reverse-engineered
                            driver for nvidia cards
 - - video_cards_r300     : VIDEO_CARDS setting to build only r300, r400 and
                            r500 based chips code for radeon
 - - video_cards_r600     : VIDEO_CARDS setting to build only r600, r700,
                            Evergreen and Northern Islands based chips code for
                            radeon
 + + video_cards_radeon   : VIDEO_CARDS setting to build driver for ATI radeon
                            video cards
 + + video_cards_radeonsi : VIDEO_CARDS setting to build only Southern Islands
                            based chips code for radeon
 - - video_cards_virgl    : VIDEO_CARDS setting to build driver for virgil
                            (virtual 3D GPU)
 - - video_cards_vmware   : VIDEO_CARDS setting to build driver for vmware
                            video cards
 + + vulkan               : Enable Vulkan drivers
 - - vulkan-overlay       : Build vulkan-overlay-layer which displays Frames
                            Per Second and other statistics
 + + wayland              : Enable support for dev-libs/wayland
 - - xa                   : Enable the XA (X Acceleration) API for Gallium3D.
 - - xvmc                 : Enable the XvMC acceleration interface for the
                            Gallium3D Video Layer.
 - - zink                 : Enable the Zink OpenGL-over-Vulkan Gallium driver
 + + zstd                 : Enable support for ZSTD compression
```

**Comment by PF4Public** [comment] 2022-06-04 18:52
Could be a wayland issue. Cannot reproduce under X11:
![image](https://user-images.githubusercontent.com/10319700/172021526-a0f79573-eba7-4294-b1dc-e748ae5d245b.png).

Have you tried disabling Vulkan in Chromium? Have you tried disabling vaapi in Chromium? Vaapi is known to be bugged with Vulkan. Apart from that I have no idea what else to try :(

**Comment by arbitrary-dev** [comment] 2022-06-11 20:44
Nice. It crashes on X as well…
```
$ equery u ungoogled-chromium 
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for www-client/ungoogled-chromium-102.0.5005.61_p3:
 U I
 - - cfi                : Build with CFI (Control Flow Integrity) enabled. It requires "-stdlib=libc++", see #40 for more details. 
 + + clang              : Use Clang compiler instead of GCC 
 - - convert-dict       : Patch and build the convert_dict utility. The script will be installed into /usr/lib64/chromium-browser/update-dicts.sh. More info here:
                          https://github.com/Eloston/ungoogled-chromium/issues/188#issuecomment-444752907 
 + + cups               : Add support for CUPS (Common Unix Printing System)
 - - custom-cflags      : Build with user-specified CFLAGS (unsupported)
 - - debug              : Enable DCHECK feature with severity configurable at runtime. Mostly intended for debugging and development, NOT RECOMMENDED for general use. 
 - - enable-driver      : Build chromedriver 
 - - gtk4               : Build with GTK4 headers. 
 + + hangouts           : Enable support for Google Hangouts features such as screen sharing 
 - - headless           : Build Ozone only with headless backend, NOT RECOMMENDED for general uses 
 - - js-type-check      : Enable JavaScript type-checking for Chrome's web technology-based UI. Requires Java. 
 - - kerberos           : Add kerberos support
 + + official           : Enable Official build instead of Developer build. 
 + + optimize-thinlto   : Whether to enable ThinLTO optimizations. Turning ThinLTO optimizations on can substantially increase link time and binary size, but they generally also make
                          binaries a fair bit faster. 
 + + optimize-webui     : Optimize parts of Chromium's UI written with web technologies (HTML/CSS/JS) for runtime performance purposes. This does more work at compile time for speed benefits
                          at runtime. 
 - - pgo                : Enable PGO. Requires clang and bundled binary profile data in sources tree. 
 - - pic                : Disable optimized assembly code that is not PIC friendly 
 + + proprietary-codecs : Enable proprietary codecs like H.264, MP3 
 + + pulseaudio         : Add support for PulseAudio sound server
 - - screencast         : Enable support for remote desktop and screen cast using media-video/pipewire
 - - suid               : Build the SUID sandbox, which is only needed on CONFIG_USER_NS=n kernels 
 + + system-ffmpeg      : Use the system media-video/ffmpeg instead of the bundled one
 + + system-harfbuzz    : Use the system media-libs/harfbuzz instead of the bundled one
 + + system-icu         : Use the system dev-libs/icu instead of the bundled one
 + + system-jsoncpp     : Use the system dev-libs/jsoncpp instead of the bundled one
 + + system-libevent    : Use the system dev-libs/libevent instead of the bundled one
 + + system-libusb      : Use the system dev-libs/libusb instead of the bundled one
 - - system-libvpx      : Use the system media-libs/libvpx instead of the bundled one
 + + system-openh264    : Use the system media-libs/openh264 instead of the bundled one. If disabled, it will restrict USE=bindist.
 + + system-openjpeg    : Use the system-wide media-libs/openjpeg instead of the bundled one. OpenJPEG use are exclusively for Chromium's PDF viewer.
 + + system-png         : Use system libpng instead of the bundled one 
 + + system-re2         : Use the system-wide dev-libs/re2 instead of the bundled one
 + + system-snappy      : Use the system-wide app-arch/snappy instead of the bundled one
 + + thinlto            : Build with ThinLTO support. LTO (Link Time Optimization) achieves better runtime performance through whole-program analysis and cross-module optimization (highly
                          recommended). 
 + + vaapi              : Enable Video Acceleration API for hardware decoding
 + + vdpau              : Enable the Video Decode and Presentation API for Unix acceleration interface
 - - wayland            : Enable dev-libs/wayland backend
 - - widevine           : Unsupported closed-source DRM capability (required by Netflix VOD)
```

**Comment by arbitrary-dev** [comment] 2022-06-11 20:45
Will try to compile it with bundled deps instead and check if it fixes the issue.

**Comment by arbitrary-dev** [comment] 2022-06-11 20:58
By the way, on your screenshot, @PF4Public, is a YouTube's internal miniplayer, but I was talking about the picture-in-picture mode provided by the chromium itself:

![areashot-2022-06-11-234842](https://user-images.githubusercontent.com/6984946/173204479-a5e668e9-626c-47a1-8083-848db02bbb6e.png)

**Comment by PF4Public** [comment] 2022-06-11 22:14
Sorry, I misunderstood. It seems similar to https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/185. May I ask you to try a patch from arch and let me know if it resolves this issue for you?

**Comment by arbitrary-dev** [comment] 2022-06-12 10:33
Yep, having the following patch fixes the issue:
```diff
$ cat /etc/portage/patches/www-client/ungoogled-chromium-102.0.5005.115_p1/disable-GlobalMediaControlsCastStartStop.patch
Disable kGlobalMediaControlsCastStartStop by default
https://crbug.com/1314342

--- a/chrome/browser/media/router/media_router_feature.cc
+++ b/chrome/browser/media/router/media_router_feature.cc
@@ -40,13 +40,8 @@
 const base::Feature kDialEnforceUrlIPAddress{"DialEnforceUrlIPAddress",
                                              base::FEATURE_DISABLED_BY_DEFAULT};
 
-#if BUILDFLAG(IS_CHROMEOS)
 const base::Feature kGlobalMediaControlsCastStartStop{
     "GlobalMediaControlsCastStartStop", base::FEATURE_DISABLED_BY_DEFAULT};
-#else
-const base::Feature kGlobalMediaControlsCastStartStop{
-    "GlobalMediaControlsCastStartStop", base::FEATURE_ENABLED_BY_DEFAULT};
-#endif  // BUILDFLAG(IS_CHROMEOS)
 
 #endif  // !BUILDFLAG(IS_ANDROID)
```

**Comment by PF4Public** [comment] 2022-06-12 14:27
But arch enables it by default :) Have you tried enabling it by default? Which of the patches should I apply in the ebuild then :)

**Comment by arbitrary-dev** [comment] 2022-06-12 15:20
From what I see here:
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/5bb97579487c1dc4a0aa3f7dc136f9da3f913bc0#diff-c13dbcca92f9ff12cd26ecce958be3f9ee8563baace04f7a463a6d2dd4252e0bR116

Arch guys took the upstream patch that enables the culprit by default, and then apply it in revert `patch -R`, disabling it so to speak.

**Comment by PF4Public** [comment] 2022-06-12 16:09
> Arch guys took the upstream patch that enables the culprit by default, and then apply it in revert `patch -R`, disabling it so to speak.

Indeed! Thanks.

**Comment by arbitrary-dev** [comment] 2023-01-20 14:16
Happening again after updating to 109.0.5414.74

**Comment by PF4Public** [comment] 2023-01-20 14:53
Looks like there is an error in https://github.com/PF4Public/gentoo-overlay/blob/13cb34ce1ccce41148ed6f8ed15ba0a932dc43b4/www-client/ungoogled-chromium/ungoogled-chromium-109.0.5414.74_p1.ebuild#L343-L346

I'll fix it soon.

**Comment by PF4Public** [comment] 2023-01-20 16:01
Please try rebuilding, I hope it should be fixed now.

**Closed** 2023-01-21 22:00 UTC
Labels: bug
