### ISSUE TITLE
ungoogled-chromium: patching file media/filters/ffmpeg_demuxer.cc fails

### ISSUE THREAD

**Issue by UnclePain** [PF4Public/gentoo-overlay#285] opened 2023-12-13 08:55 UTC
Building ungoogled-chromium 119 and upwards reproducibly fails on my system at the following step:

```
 * Applying chromium-118-ffmpeg.patch ...
patching file media/filters/ffmpeg_demuxer.cc
Hunk #1 FAILED at 398.
Hunk #2 succeeded at 453 (offset -8 lines).
1 out of 2 hunks FAILED -- saving rejects to file media/filters/ffmpeg_demuxer.cc.rej
```

Please find attached:

- the build log: [build.log.txt](https://github.com/PF4Public/gentoo-overlay/files/13658564/build.log.txt)
- emerge --info: [emerge-info.txt](https://github.com/PF4Public/gentoo-overlay/files/13658555/emerge-info.txt)
- the patch reject file: [ffmpeg_demuxer.cc.rej.txt](https://github.com/PF4Public/gentoo-overlay/files/13658557/ffmpeg_demuxer.cc.rej.txt)

**Comment by PF4Public** [comment] 2023-12-13 10:43
Which version of ffmpeg do you have? Is it a duplicate of https://github.com/PF4Public/gentoo-overlay/issues/272?

**Comment by UnclePain** [comment] 2023-12-13 11:01
```
ffmpeg version 4.4.4 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (Gentoo Hardened 13.2.1_p20230826 p7)
configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --docdir=/usr/share/doc/ffmpeg-4.4.4-r6/html --mandir=/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --nm=x86_64-pc-linux-gnu-nm --strip=x86_64-pc-linux-gnu-strip --ranlib=x86_64-pc-linux-gnu-ranlib --pkg-config=x86_64-pc-linux-gnu-pkg-config --optflags='-march=native -O3 -mfpmath=sse -pipe' --disable-static --enable-avfilter --enable-avresample --disable-stripping --disable-optimizations --disable-libcelt --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=oss --disable-indev=sndio --disable-outdev=oss --disable-outdev=sndio --enable-version3 --enable-version3 --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --enable-gnutls --enable-gmp --enable-gpl --disable-hardcoded-tables --enable-iconv --disable-libxml2 --enable-lzma --enable-network --disable-opencl --disable-openssl --enable-postproc --disable-libsmbclient --enable-ffplay --enable-sdl2 --enable-vaapi --enable-vdpau --enable-vulkan --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --enable-openal --enable-opengl --disable-libv4l2 --disable-libpulse --enable-libdrm --enable-libjack --enable-libopencore-amrwb --enable-libopencore-amrnb --disable-libcodec2 --enable-libdav1d --disable-libfdk-aac --enable-libopenjpeg --disable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 --disable-mmal --enable-libmodplug --enable-libopus --disable-libmfx --disable-libilbc --disable-librtmp --disable-libssh --enable-libspeex --disable-libsrt --enable-librsvg --disable-ffnvcodec --enable-libvorbis --enable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --disable-chromaprint --disable-cuda-llvm --disable-libflite --disable-frei0r --disable-libvmaf --disable-libfribidi --enable-fontconfig --disable-ladspa --enable-libass --disable-libtesseract --enable-lv2 --enable-libfreetype --disable-libvidstab --disable-librubberband --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-amf --disable-libvo-amrwbenc --disable-libkvazaar --disable-libaom --enable-libmp3lame --disable-libopenh264 --disable-librav1e --disable-libsnappy --disable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-vsx --disable-power8 --disable-amd3dnow --disable-amd3dnowext --disable-fma4 --disable-xop --enable-pic --cpu=host --disable-doc --disable-htmlpages --enable-manpages
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

In #272 you suggested switch to ffmpeg 6, but I have several packages installed that depend on version 4 (like vlc, even in its Git ebuild).

**Comment by PF4Public** [comment] 2023-12-13 13:28
Quote from https://github.com/PF4Public/gentoo-overlay/issues/272#issuecomment-1793776845
>I would suggest you switch to ffmpeg-6 or disable system-ffmpeg. I'm afraid I won't have time soon to update the patch.

**Closed by PF4Public** 2023-12-13 13:28 UTC
Labels: bug

**Comment by UnclePain** [comment] 2023-12-13 16:13
For everyone from the future: Upgrading to ffmpeg 6 indeed helped. If you want to keep vlc around, you need to upgrade to vlc 4, which is currently only available in Portage through media-video/vlc-9999.
