### ISSUE TITLE
www-client/ungoogled-chromium-113.0.5672.63_p1: Build failure with clang 15, libc++

### ISSUE THREAD

**Issue by LeFroid** [PF4Public/gentoo-overlay#222] opened 2023-05-06 17:21 UTC
Ebuild flags
`
[ebuild     U  ] www-client/ungoogled-chromium-113.0.5672.63_p1::pf4public [112.0.5615.49_p1::pf4public] USE="X cfi clang cups custom-cflags official pic proprietary-codecs pulseaudio qt5 (selinux) thinlto vaapi -convert-dict -debug -enable-driver -gtk4 -hangouts -headless -hevc -kerberos -nvidia% -optimize-thinlto -optimize-webui -pgo -screencast -suid -system-abseil-cpp% -system-av1 -system-brotli% -system-crc32c% -system-double-conversion% -system-ffmpeg -system-harfbuzz -system-icu -system-jsoncpp -system-libevent -system-libusb -system-libvpx -system-openh264 -system-openjpeg -system-png -system-re2 -system-snappy -system-woff2% -wayland -widevine" L10N="af am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW" 0 KiB
`

Using clang 15 with libc++, compiler settings below
```
CC="clang"
CXX="clang++"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
LDFLAGS="${LDFLAGS} -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,--as-needed"

_HARDENING_FLAGS="-fPIC -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fvisibility=hidden"
CFLAGS="${CFLAGS} ${_HARDENING_FLAGS} -flto=thin"
CXXFLAGS="${CXXFLAGS} ${_HARDENING_FLAGS} -flto=thin -stdlib=libc++"
LDFLAGS="${LDFLAGS} -unwindlib=libunwind -stdlib=libc++"
```

Getting the following error during compilation
```
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:537:28: error: reference to local binding 'grid_items' declared in enclosing function 'blink::NGGridLayoutAlgorithm::BuildGridSizingSubtree'
    for (auto& grid_item : grid_items) {
                           ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:519:10: note: 'grid_items' declared here
  auto& [grid_items, layout_data, subtree_size] =
         ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:547:5: error: reference to local binding 'layout_data' declared in enclosing function 'blink::NGGridLayoutAlgorithm::BuildGridSizingSubtree'
    layout_data.SetTrackCollection(
    ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:519:22: note: 'layout_data' declared here
  auto& [grid_items, layout_data, subtree_size] =
                     ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1547:67: error: reference to local binding 'layout_data' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
    InitializeTrackCollection(opt_subgrid_data, track_direction, &layout_data);
                                                                  ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:22: note: 'layout_data' declared here
  auto& [grid_items, layout_data, subtree_size] =
                     ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1549:9: error: reference to local binding 'layout_data' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
    if (layout_data.HasSubgriddedAxis(track_direction)) {
        ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:22: note: 'layout_data' declared here
  auto& [grid_items, layout_data, subtree_size] =
                     ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1551:44: error: reference to local binding 'layout_data' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
                                         ? layout_data.Columns()
                                           ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:22: note: 'layout_data' declared here
  auto& [grid_items, layout_data, subtree_size] =
                     ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1552:44: error: reference to local binding 'layout_data' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
                                         : layout_data.Rows();
                                           ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:22: note: 'layout_data' declared here
  auto& [grid_items, layout_data, subtree_size] =
                     ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1553:30: error: reference to local binding 'grid_items' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
      for (auto& grid_item : grid_items) {
                             ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:10: note: 'grid_items' declared here
  auto& [grid_items, layout_data, subtree_size] =
         ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1557:32: error: reference to local binding 'layout_data' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
      auto& track_collection = layout_data.SizingCollection(track_direction);
                               ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:22: note: 'layout_data' declared here
  auto& [grid_items, layout_data, subtree_size] =
                     ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1558:51: error: reference to local binding 'grid_items' declared in enclosing function 'blink::NGGridLayoutAlgorithm::InitializeTrackSizes'
      CacheGridItemsProperties(track_collection, &grid_items);
                                                  ^
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:1543:10: note: 'grid_items' declared here
  auto& [grid_items, layout_data, subtree_size] =
         ^
9 errors generated.
```

Not sure if I'm using some unsupported configuration, but this is the first time I've ran into the issue with ungoogled-chromium. All the previous versions compiled just fine.

Edit: Looks like this may be an issue with LLVM 15, per this issue: https://github.com/NixOS/nixpkgs/issues/213862
Perhaps the fix is to require LLVM/clang 16 or greater

**Comment by PF4Public** [comment] 2023-05-06 17:36
Duplicate of #220

**Closed by PF4Public** 2023-05-06 17:36 UTC
Labels: bug
