### ISSUE TITLE
www-client/ungoogled-chromium-113.0.5672.63_p1: out/Release v8_context_snapshot_generator failed

### ISSUE THREAD

**Issue by arbitrary-dev** [PF4Public/gentoo-overlay#220] opened 2023-05-05 12:34 UTC
[build.log.gz](https://github.com/PF4Public/gentoo-overlay/files/11406258/build.log.gz)

```
ninja: build stopped: subcommand failed.
 * ERROR: www-client/ungoogled-chromium-113.0.5672.63_p1::pf4public failed (compile phase):
 *   ninja -v -j13 -l12 -C out/Release v8_context_snapshot_generator failed
```

```
$ cat package.use
www-client/ungoogled-chromium hangouts optimize-webui system-openjpeg vaapi vdpau
www-client/ungoogled-chromium optimize-thinlto thinlto
```

**Comment by logrusx** [comment] 2023-05-05 12:47
This is the actual error:
../../third_party/blink/renderer/core/layout/ng/grid/ng_grid_layout_algorithm.cc:537:28: error: reference to local binding 'grid_items' declared in enclosing        function 'blink::NGGridLayoutAlgorithm::BuildGridSizingSubtree'
     for (auto& grid_item : grid_items) {
and a few more of the same type.
I think the issue is in clang: [reddit](https://www.reddit.com/r/LLVM/comments/s0ykcj/why_does_clang_fail_with_error_reference_to_local/)

**Comment by PF4Public** [comment] 2023-05-05 13:57
Oh, I forgot about that. If you're using clang before 16, you need additional patches:
https://github.com/ungoogled-software/ungoogled-chromium/pull/2329#:~:text=header%3A%20%5B4372590%5D-,Toolchain%2Drelated%20fixes%3A,diff,-Change%20log%0ABlog

I don't know. Maybe I should apply them vonditionally?

**Comment by logrusx** [comment] 2023-05-06 06:21
> Oh, I forgot about that. If you're using clang before 16, you need additional patches: [https://github.com/ungoogled-software/ungoogled-chromium/pull/2329](https://github.com/ungoogled-software/ungoogled-chromium/pull/2329#:~:text=header%3A%20%5B4372590%5D-,Toolchain%2Drelated%20fixes%3A,diff,-Change%20log%0ABlog)
> 
> I don't know. Maybe I should apply them conditionally?

I believe that, in the official chromium ebuild, they've solved the problem the same way as we discussed in #86, this time doing it in pkg_setup.

**Comment by logrusx** [comment] 2023-05-06 13:37
On another note, I have some pages breaking, maybe it's better to push 113 back for a while.

**Comment by PF4Public** [comment] 2023-05-06 13:53
> On another note, I have some pages breaking, maybe it's better to push 113 back for a while.

I'm on 113 for a week already and no issues so far.

>I believe that, in the official chromium ebuild, they've solved the problem the same way as we discussed in https://github.com/PF4Public/gentoo-overlay/issues/86, this time doing it in pkg_setup:

That's not as simple as it may seem. On one hand, clang-15 is perfectly capable of building 113, it needs some small fixes. On the other hand clang-16 is still testing in Gentoo (last time I checked at least.) thus it would be unreasonable to depend on it in stable.

**Comment by logrusx** [comment] 2023-05-07 08:39
> On the other hand clang-16 is still testing in Gentoo
They've masked libcxx and lto use flags which cause the ebuild use and pull in clang 16, so I guess they don't have such concerns on their side. I personally decided to downgrade to 112 from a bin pkg I had stashed while investigating an unrelated issue.
Honestly I don't have arguments supporting one option over the other. If it were me I'd rather try to automate things as much as possible so that they are as complete as possible, so I guess my completely irrational choice would be towards applying the patches.

**Comment by PF4Public** [comment] 2023-05-07 12:47
I decided to include clang-15 patches anyway. So this should be fixed now.

**Closed by PF4Public** 2023-05-07 12:47 UTC
Labels: bug

**Comment by arbitrary-dev** [comment] 2023-06-11 09:20
Build fails for `www-client/ungoogled-chromium-114.0.5735.106_p1` again...

```
../../media/base/cdm_promise_adapter.cc:99:66: error: reference to local binding 'promise_id' declared in enclosing function 'media::CdmPromiseAdapter::Clear'
        "media", "CdmPromise", TRACE_ID_WITH_SCOPE("CdmPromise", promise_id),
                                                                 ^
../../media/base/cdm_promise_adapter.cc:97:15: note: 'promise_id' declared here
  for (auto& [promise_id, promise] : promises_) {
```

**Comment by mortezadadgar** [comment] 2023-06-11 09:28
this happened to me as well with following use flags
```
www-client/ungoogled-chromium thinlto optimize-webui optimize-thinlto convert-dict system-brotli system-crc32c system-double-conversion system-openjpeg system-woff2
```

**Comment by PF4Public** [comment] 2023-06-11 10:16
Please file new issue if you're about to report a new one!
