### ISSUE TITLE
www-client/ungoogled-chromium-78.0.3904.87_p1: error: use of undeclared identifier 'CONSTRAINED_FROM_ABOVE_DROP'; did you mean 'CONSTRAINED_LAYER_DROP'?

### ISSUE THREAD

**Issue by perfect7gentleman** [PF4Public/gentoo-overlay#11] opened 2019-11-03 09:49 UTC
```
../../third_party/webrtc/modules/video_coding/codecs/vp9/vp9_impl.cc:761:40: error: use of undeclared identifier 'CONSTRAINED_FROM_ABOVE_DROP'; did you mean 'CONSTRAINED_LAYER_DROP'?
      svc_drop_frame_.framedrop_mode = CONSTRAINED_FROM_ABOVE_DROP;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       CONSTRAINED_LAYER_DROP
/usr/include/vpx/vp8cx.h:838:3: note: 'CONSTRAINED_LAYER_DROP' declared here
  CONSTRAINED_LAYER_DROP,
  ^
1 error generated.
ninja: subcommand failed
```
```
~ $ qlist -Iv vpx
media-libs/libvpx-1.8.1
```

**Comment by PF4Public** [comment] 2019-11-03 10:12
Duplicate of #10

**Comment by PF4Public** [comment] 2019-11-03 10:14
Wait a minute. It does not work with 1.8.1?

**Closed** 2019-11-03 10:17 UTC
Labels: bug

**Comment by perfect7gentleman** [comment] 2019-11-03 10:34
chromium-77 works with 1.8.1
