### ISSUE TITLE
dev-util/electron: LLVM Packages got renamed

### ISSUE THREAD

**Issue by MarkusTieger** [PF4Public/gentoo-overlay#400] opened 2024-12-17 14:24 UTC
Some llvm packages, which are used as dependency in electron, got renamed in the gentoo repo.
For example:
sys-devel/clang -> llvm-core/clang
sys-devel/lld -> llvm/core/lld

The dependencies in this repo (for example dev-util/electron) didn't get renamed though.

**Comment by PF4Public** [comment] 2024-12-17 17:40
Duplicate of #398

**Closed by PF4Public** 2024-12-17 17:40 UTC
Labels: bug
