### ISSUE TITLE
Thinlto failure

### ISSUE THREAD

**Issue by moroznah** [PF4Public/gentoo-overlay#58] opened 2020-11-13 17:04 UTC
**Description**
ungoogled-chromium-86.0.4240.193_p1 fails to build

**How to Reproduce**
Relevant USE flags:
>www-client/ungoogled-chromium cfi clang convert-dict cups hangouts optimize-thinlto optimize-webui proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-openh264 system-openjpeg tcmalloc thinlto vaapi widevine
sys-devel/clang default-compiler-rt default-libcxx default-lld static-analyzer xml
sys-devel/clang-runtime compiler-rt libcxx openmp sanitize
sys-devel/llvm libffi ncurses xml z3
sys-libs/compiler-rt clang
sys-libs/libcxx libunwind static-libs
sys-libs/libcxxabi libunwind static-libs
sys-libs/libunwind static-libs

>gcc (Gentoo Hardened 10.2.0-r3 p4) 10.2.0
clang version 10.0.1
lld-10.0.1

I do have GentooLTO overlay and distcc used system wide, however for this build env was just blank -O3 -march=native -mtune-native .

**Expected behavior**
It should built.

**Actual behavior**
Fails at the very end of build, please see attached log.

**Logs**
<pre><code>
[20562/20562] x86_64-pc-linux-gnu-clang++ -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O2 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -fsanitize=cfi-vcall -fsanitize=cfi-derived-cast -fsanitize=cfi-unrelated-cast -fsanitize=cfi-icall -pie -Wl,--disable-new-dtags -Wl,--icf=none -Wl,-O1 -Wl,--as-needed -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=4 -o "./v8_context_snapshot_generator" -Wl,--start-group @"./v8_context_snapshot_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -ljsoncpp -licui18n -licuuc -licudata -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lz -levent -ljpeg -lpng16 -lxml2 -lxslt -lresolv -lgio-2.0 -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lfontconfig -lharfbuzz-subset -lharfbuzz -lm -lopus -lavcodec -lavformat -lavutil -lopenh264 -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lX11-xcb -lxcb -lxcb-dri3 -ldrm -lre2 -lXi -lpci -lgbm -ldbus-1 -lasound -lpulse -lsnappy -lcups -latk-1.0 -latk-bridge-2.0 -lpangocairo-1.0 -lpango-1.0 -lcairo -lva
FAILED: v8_context_snapshot_generator 
x86_64-pc-linux-gnu-clang++ -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O2 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -fsanitize=cfi-vcall -fsanitize=cfi-derived-cast -fsanitize=cfi-unrelated-cast -fsanitize=cfi-icall -pie -Wl,--disable-new-dtags -Wl,--icf=none -Wl,-O1 -Wl,--as-needed -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=4 -o "./v8_context_snapshot_generator" -Wl,--start-group @"./v8_context_snapshot_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -ljsoncpp -licui18n -licuuc -licudata -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lz -levent -ljpeg -lpng16 -lxml2 -lxslt -lresolv -lgio-2.0 -lwebpdemux -lwebpmux -lwebp -lfreetype -lexpat -lfontconfig -lharfbuzz-subset -lharfbuzz -lm -lopus -lavcodec -lavformat -lavutil -lopenh264 -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lX11-xcb -lxcb -lxcb-dri3 -ldrm -lre2 -lXi -lpci -lgbm -ldbus-1 -lasound -lpulse -lsnappy -lcups -latk-1.0 -latk-bridge-2.0 -lpangocairo-1.0 -lpango-1.0 -lcairo -lva
ld.lld: error: undefined symbol: Json::Reader::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Json::Value&, bool)
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))

ld.lld: error: undefined symbol: Json::Value::isMember(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced 16 more times

ld.lld: error: undefined symbol: Json::Value::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced by echo_canceller3_config_json.cc
>>>               thinlto-cache/Thin-5234f9.tmp.o:(webrtc::Aec3ConfigFromJsonString(absl::string_view, webrtc::EchoCanceller3Config*, bool*))
>>> referenced 16 more times

ld.lld: error: undefined symbol: Json::Value::asString() const
>>> referenced by json.cc
>>>               thinlto-cache/Thin-22fd64.tmp.o:(rtc::GetBoolFromJson(Json::Value const&, bool*))
>>> referenced by json.cc
>>>               thinlto-cache/Thin-22fd64.tmp.o:(rtc::GetBoolFromJson(Json::Value const&, bool*))
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
 * ERROR: www-client/ungoogled-chromium-86.0.4240.193_p1::pf4public failed (compile phase):
 *   ninja -v -j4 -l0 -C out/Release v8_context_snapshot_generator failed
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 5972:  Called eninja '-C' 'out/Release' 'v8_context_snapshot_generator'
 *   environment, line 3426:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=www-client/ungoogled-chromium-86.0.4240.193_p1::pf4public'`,
 * the complete build log and the output of `emerge -pqv '=www-client/ungoogled-chromium-86.0.4240.193_p1::pf4public'`.
 * 
 * MemTotal:       16186684 kB
 * SwapTotal:       4194300 kB
 * 
 * The complete build log is located at '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/work/chromium-86.0.4240.193'
 * S: '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/work/chromium-86.0.4240.193'

>>> Failed to emerge www-client/ungoogled-chromium-86.0.4240.193_p1, Log file:

>>>  '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/temp/build.log'

 * Messages for package www-client/ungoogled-chromium-86.0.4240.193_p1:

 * 
 * Building with cfi is only possible if building with -stdlib=libc++
 * Make sure all dependencies are also built this way, see #40
 * 

 * Messages for package www-client/ungoogled-chromium-86.0.4240.193_p1:

 * Even though ungoogled-chromium is built with vaapi support, #ignore-gpu-blacklist
 * should be enabled via flags or commandline for it to work.
 * lto-overlay: filter-flags OVERRIDDEN
 * lto-overlay: strip-flags OVERRIDDEN
 * lto-overlay: filter-flags OVERRIDDEN
 * lto-overlay: append-flags OVERRIDDEN
 * ERROR: www-client/ungoogled-chromium-86.0.4240.193_p1::pf4public failed (compile phase):
 *   ninja -v -j4 -l0 -C out/Release v8_context_snapshot_generator failed
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 5972:  Called eninja '-C' 'out/Release' 'v8_context_snapshot_generator'
 *   environment, line 3426:  Called die
 * The specific snippet of code:
 *       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=www-client/ungoogled-chromium-86.0.4240.193_p1::pf4public'`,
 * the complete build log and the output of `emerge -pqv '=www-client/ungoogled-chromium-86.0.4240.193_p1::pf4public'`.
 * The complete build log is located at '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/work/chromium-86.0.4240.193'
 * S: '/var/tmp/portage/www-client/ungoogled-chromium-86.0.4240.193_p1/work/chromium-86.0.4240.193'
</code></pre>
[build.log.zip](https://github.com/PF4Public/gentoo-overlay/files/5538306/build.log.zip)
[environment.zip](https://github.com/PF4Public/gentoo-overlay/files/5538312/environment.zip)

**Additional context**
This seems to be very similar to https://github.com/PF4Public/gentoo-overlay/issues/49
I'd test on this system without lto to provide comprehensive comparison with different use flags, however it's a 36 hour pain on XPS 13 wooden CPU without distcc :smile:

**Comment by perfect7gentleman** [comment] 2020-11-13 22:23
rebuild jsconcpp with Clang.

**Comment by PF4Public** [comment] 2020-11-13 23:22
I'd say, it is exactly the same. I would have suggested that you continued the discussion in the existing issue instead of creating another one, but given that that one is closed, okay, fine, lets keep this one open in case someone also encounters it.

Like I said in the bug you mention, it must have something to do with your system, the way your compiler is built or your usage of libcxx.

Upon every release I build [all of them](https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/86.0.4240.198-1) except x86 with thinlto without issues.

Not sure if I can help with this, but let's start with checking `/var/db/pkg/sys-devel/clang-*/CXXFLAGS` and `/var/db/pkg/sys-devel/clang-*/LDFLAGS`
Also suspiscious are these lines:
```
 * lto-overlay: filter-flags OVERRIDDEN
 * lto-overlay: strip-flags OVERRIDDEN
 * lto-overlay: filter-flags OVERRIDDEN
 * lto-overlay: append-flags OVERRIDDEN
```
But they don't seem to do any difference, apart from ignoring optimizations predefined by Chromium developers and using -O3 and other flags. That's not how the compilation is intended by the ebuild, but that's up to you. At least this does not harm. Apart from that I see nothing obviously wrong in your logs, so I'd suppose the problem is figuratively speaking "before" you try to compile ungoogled-chromium.

**Comment by moroznah** [comment] 2020-11-14 00:00
> rebuild jsconcpp with Clang.

Thanks for the tip! Is just jsoncpp enough or should i do also dev-libs/re2 or any other deps? I use Clang only for browsers, rest of the system is GCC compiled and i'm not sure what will happen with other packages depending on jsoncpp. Is specifiying ungoogled-chromium USE flag -system-jsoncpp a valid alternative to not touching jsoncpp package?



> I'd say, it is exactly the same. I would have suggested that you continued the discussion in the existing issue instead of creating another one, but given that that one is closed, okay, fine, lets keep this one open in case someone also encounters it.
> 
> Like I said in the bug you mention, it must have something to do with your system, the way your compiler is built or your usage of libcxx.
> 
> Upon every release I build [all of them](https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/86.0.4240.198-1) except x86 with thinlto without issues.

Can you please elaborate on possible faults due to different libcxx usage?

> Not sure if I can help with this, but let's start with checking `/var/db/pkg/sys-devel/clang-*/CXXFLAGS` and `/var/db/pkg/sys-devel/clang-*/LDFLAGS`
> Also suspiscious are these lines:
> 
> ```
>  * lto-overlay: filter-flags OVERRIDDEN
>  * lto-overlay: strip-flags OVERRIDDEN
>  * lto-overlay: filter-flags OVERRIDDEN
>  * lto-overlay: append-flags OVERRIDDEN
> ```
> 
> But they don't seem to do any difference, apart from ignoring optimizations predefined by Chromium developers and using -O3 and other flags. That's not how the compilation is intended by the ebuild, but that's up to you. At least this does not harm. Apart from that I see nothing obviously wrong in your logs, so I'd suppose the problem is figuratively speaking "before" you try to compile ungoogled-chromium.

My stock CFLAGS are quite unusable with clang:
>-O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fuse-linker-plugin -march=skylake -mmmx -msse -msse2 -msse3 -mssse3 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mfma -mbmi -msgx -mbmi2 -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mclflushopt -mxsavec -mxsaves --param=l1-cache-size=32 --param=l1-cache-line-size=64 --param=l2-cache-size=4096 -mtune=skylake -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -feliminate-unused-debug-types -ftree-vectorize -ftree-loop-vectorize -ftree-loop-distribution -ftree-loop-distribute-patterns -fasynchronous-unwind-tables -D_FORTIFY_SOURCE=2 -fstack-protector-all -fstack-clash-protection -fexceptions -mindirect-branch=thunk -mfunction-return=thunk --param=ssp-buffer-size=32

Lto-overlay lines in build log actually aren't doing anything (apart from 'OVERRIDDEN' in logs), since i've set manual env, excluding all GentooLTO flags. The actual flags for chromium build are:
>PLATFORMOPT="-march=skylake -mmmx -msse -msse2 -msse3 -mssse3 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mfma -mbmi -msgx -mbmi2 -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mclflushopt -mxsavec -mxsaves --param=l1-cache-size=32 --param=l1-cache-line-size=64 --param=l2-cache-size=4096 -mtune=skylake -mprefer-vector-width=256 -falign-functions=32"
CFLAGS="-O3 ${PLATFORMOPT} -pipe"
CXXFLAGS="${CFLAGS}"
MAKEOPTS="-j4"
FEATURES="-distcc"

Didn't override LDFLAGS tho, but will for next build attempt.

I've just figured out that distcc is quite usable with clang. I'll add clang do adjacent servers and will be able to try out other configurations within sane timeframe. I'll deal with jsoncpp at start, that was a valid point.

**Comment by PF4Public** [comment] 2020-11-14 00:38
> Can you please elaborate on possible faults due to different libcxx usage?

Gentoo uses `CHROMIUM_FORCE_LIBCXX` in chromium:
https://github.com/gentoo-mirror/gentoo/blob/fda5f0a370ae6a6cb899daff14d1e963a939de0e/www-client/chromium/chromium-86.0.4240.198.ebuild#L139-L152

But this is hardly manageable with system-* USE flags, so I decided not to have such a conditional. Which in turn means, that a user is responsible on ensuring all the necessary dependencies are properly compiled with libcxx. This is especially true if using `cfi`.

More specifically, a user is responsible on ensuring proper linking if using both libc++ and libstdc++. @perfect7gentleman could probably add something, because AFAIA he did compile ungoogled-chromium with libstdc++ some time ago.

**Comment by perfect7gentleman** [comment] 2020-11-14 05:02
AFIAIK, only jsoncpp and re2 should be compiled with Clang+libc++ if Chromium is compiled with Clang+libc++ + USE=system-jsoncpp.
Using with distcc among machines with different toolchains is not rather smart idea.

**Comment by PF4Public** [comment] 2020-11-14 10:28
If that is the case, I should probably write yet another warning in ebuild if both libc++ and libstdc++ are avilable.

**Comment by moroznah** [comment] 2020-11-14 11:44
Thanks for the tips guys!
It seems that i have everything Clang related using libc++, but i missed jsoncpp and re2 from previous issues.

I know the quirks about distcc, even with GCC the toolchain versions and flags should better be the same on all machines. I have a simple script that checks this and warns me about different versions and flags, which worked quite well so far for servers. I'm doing same thing for Clang toolchain now. There's just no other easy ways without distcc to test different flags in chromium, it would take months...
Clang compiled jsoncpp and re2 with distcc would mean resorting to ugly hacks, so i'm gonna disable for now system-jsoncpp, and will try without cfi and lto for starters.
Will keep you posted soon, Clang toolchain is building on servers.

**Comment by moroznah** [comment] 2020-11-16 20:51
Well, no luck with distcc - it rejects Clang jobs even on localhost. 
So i did a run again, with lto disabled, precompiled re2 by Clang with following flags: 
>clang convert-dict cups hangouts proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-libevent system-openh264 system-openjpeg tcmalloc vaapi widevine

It compiled just fine. Will try with lto now, i guess @perfect7gentleman was right.

**Comment by PF4Public** [comment] 2020-11-17 10:11
BTW @moroznah you could use [gb-chroot](https://github.com/PF4Public/gentoo-overlay/tree/master/app-admin/gb-chroot) to build binpkgs on servers and use them on your laptop. That's what I do.

**Comment by moroznah** [comment] 2020-11-17 11:47
I still haven't given up on Clang + distcc tho. It is working for other people, i'm doing something wrong probably. GCC + distcc is working flawlessly and is a big help for cross compiling on Rpi4. There is the pain for maintaining same versions of toolchains, pump mode problems etc.
@PF4Public i haven't considered chroot for bin compiling and distribution, your scripts are great to do so. Maybe i will do this for Clang, since it's only for browsers and some CPU miners for now.

Btw, ungoogled-chromium lto enabled compilation is past last failure point. The only difference now is -system-jsoncpp flag and Clang compiled re2.
I'm doing simple browser benching informatively, will do so for your ebuild once it's finished. Forgot to bench it without lto tho. FYI, current results:
>https://browserbench.org/Speedometer2.0/
Core i7-7560U
Mickeysoft 10 Edge 44.19041.423.0: 26.7+-0.7
Focal Brave 1.15.75 (86.0.4240.99): 37.3+-18
Focal Firefox 82.0.3: 44+-1.5
Focal Chromium 87.0.4280.20: 53.9+-4.9
Gentoo Chromium(1) 86.0.4240.198: 59.3+-2.5
Focal Chrome 86.0.4240.75: 	63.4+-0.7
(1) GCC10.2, -march=native, not really lto/graphite since flag-o-matic overrides them mostly

Will update once the build finished.

**Comment by moroznah** [comment] 2020-11-17 22:23
Problem solved, thanks for help. 
For anyone having same problem compile re2 with Clang and disable system jsoncpp with -system-jsoncpp USE flag.

**Comment by PF4Public** [comment] 2020-11-18 11:45
How do you think, will it be sufficient to issue a warning like this:
```
	if has_version "sys-libs/libcxx"; then
		ewarn
		ewarn "You have sys-libs/libcxx, please make sure that"
		ewarn "all c++ dependencies are compiled with the same library"
		ewarn "most notably: dev-libs/re2 and dev-libs/jsoncpp"
		ewarn "see #58 #49 for details"
		ewarn
	fi
```

**Comment by moroznah** [comment] 2020-11-18 12:20
Let's summerrize all compilation runs to get to the bottom of this issue (all with libcxx):

1) Run from here https://github.com/PF4Public/gentoo-overlay/issues/49 . jsoncpp and re2 compiled by GCC. system-jsoncpp USE flag is set. Failure.
2) My original run, both re2 and jsoncpp not compiled by Clang, system-jsoncpp USE flag is set. Failure at the same stage as (1).
3) My last run, re2 is compiled by Clang, jsoncpp compiled by GCC, system-jsoncpp USE flag is UNset. Success.

(1) and (3) are closer and have just one difference - system-jsoncpp USE flag. In case (1) with this flag set even with jsoncpp lib compiled by Clang it still failed. It would seem there is a bug somewhere related to jsoncpp lib.

I'm not any expert in ebuilds, but would suggest to modify this warning: keep the re2 warning, tell user to avoid system-jsoncpp when using libcxx at all.

**Comment by PF4Public** [comment] 2020-11-18 12:41
>compiled by Clang

Is a vague term IMHO. Clang could link to any c++ library, so this is not indicative of an issue.

**Comment by perfect7gentleman** [comment] 2020-11-18 14:01
I don't know what you have done with your LLVM/Clang toolchain, but I have the following:
```
www-client/ungoogled-chromium-86.0.4240.198_p1::pf4public was built with the following:
USE="clang convert-dict cups custom-cflags optimize-thinlto optimize-webui proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-openh264 system-openjpeg tcmalloc thinlto vaapi -cfi -closure-compile -enable-driver -hangouts -headless -kerberos -ozone -ozone-wayland (-selinux) -suid -system-libvpx -vdpau -widevine" L10N="ru -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_9 -python3_6 -python3_7 -python3_8"
CFLAGS="-march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
CXXFLAGS="-march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -flax-vector-conversions=all -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync metadata-transfer multilib-strict network-sandbox news parallel-fetch parallel-install pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,--lto-O3 -Wl,--thinlto-jobs=9 -Wl,-z,norelro -fuse-ld=lld -stdlib=libc++ -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=9"
```
re2 and jsoncpp are built with the same LLVM/Clang

**Comment by moroznah** [comment] 2020-11-18 14:27
> I don't know what you have done with your LLVM/Clang toolchain, but I have the following:
> 
> ```
> www-client/ungoogled-chromium-86.0.4240.198_p1::pf4public was built with the following:
> USE="clang convert-dict cups custom-cflags optimize-thinlto optimize-webui proprietary-codecs pulseaudio system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-openh264 system-openjpeg tcmalloc thinlto vaapi -cfi -closure-compile -enable-driver -hangouts -headless -kerberos -ozone -ozone-wayland (-selinux) -suid -system-libvpx -vdpau -widevine" L10N="ru -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" PYTHON_TARGETS="python2_7 python3_9 -python3_6 -python3_7 -python3_8"
> CFLAGS="-march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
> CXXFLAGS="-march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -stdlib=libc++ -flax-vector-conversions=all -Wno-unknown-warning-option -Wno-builtin-macro-redefined"
> FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync metadata-transfer multilib-strict network-sandbox news parallel-fetch parallel-install pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
> LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,--lto-O3 -Wl,--thinlto-jobs=9 -Wl,-z,norelro -fuse-ld=lld -stdlib=libc++ -rtlib=compiler-rt -unwindlib=libunwind -s -march=native -mtune=native -O3 -mllvm -polly -pipe -fdata-sections -ffunction-sections -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -fno-asynchronous-unwind-tables -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables -Wl,-plugin-opt,-import-instr-limit=30 -Wl,--thinlto-jobs=9"
> ```
> 
> re2 and jsoncpp are built with the same LLVM/Clang

I would agree that i have something wrong with the toolchain, however i'm not the only one https://github.com/PF4Public/gentoo-overlay/issues/49 . 
By looking at your flags i think we both missed -stdlib=libc++ for jsoncpp env.
For re2 it seems irrelevant, it was built and works:
>clang++ -c -o obj/so/re2/unicode_groups.o -fPIC  -std=c++11 -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I.  -DRE2_USE_ICU  -O3 -march=native -mtune=native -fno-lto -pipe -DNDEBUG re2/unicode_groups.cc

In any case it's working fine for me with -system-jsoncpp , adding some sort of warning as @PF4Public suggested is a good idea.

**Comment by PF4Public** [comment] 2020-11-18 14:59
I've added a warning into ebuild, feel free to close the issue if it is now resolved.

**Closed** 2020-11-18 18:48 UTC
Labels: bug, help wanted
